FROM public.ecr.aws/lambda/python:3.10 AS requirements_txt

ARG POETRY_VERSION=1.4.2

RUN pip3 install --upgrade pip && \
    pip3 install poetry==${POETRY_VERSION}
COPY poetry.lock pyproject.toml ./
RUN poetry export > /requirements.txt

FROM public.ecr.aws/lambda/python:3.10


COPY --from=requirements_txt /requirements.txt /requirements.txt
RUN pip3 install -r /requirements.txt --target "${LAMBDA_TASK_ROOT}" && \
    rm /requirements.txt

RUN mount=type=cache,target=/var/cache/yum && \
    yum -y update && \
    python -m playwright install chromium

# Copy function code
COPY lambda_chat.py ${LAMBDA_TASK_ROOT}

CMD ["lambda_chat.lambda_handler"]
